# Generated by Django 4.2 on 2023-05-16 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_itemhold'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemHold',
            new_name='BasketItem',
        ),
    ]
