# Generated by Django 4.2 on 2023-05-16 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_itemhold_basketitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basketitem',
            old_name='product_id',
            new_name='product_name',
        ),
    ]
