# Generated by Django 4.2 on 2023-05-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_product_id_basketitem_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='product_name',
            field=models.TextField(),
        ),
    ]
